version: "3"

services:
  db:
    image: postgres:12
    container_name: db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=H6CcA5SeyB49G0qhMkrW
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - backend

  api-node:
    image: api-node:1
    container_name: api-node
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    networks:
      - backend

volumes:
  pg-data:
networks:
  backend:
