version: "3"

services:
  db:
    image: postgres:12
    container_name: db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=H6CcA5SeyB49G0qhMkrW
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pg-data:
networks:
  backend:
