version: "3"

x-api-common: &x-api-common
  environment:
    - DATABASE_URL=${DATABASE_URL}
  links:
    - db
  networks:
    - backend
    - frontend
  depends_on:
    db:
      condition: service_healthy

services:
  db:
    image: postgres:12
    container_name: db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=H6CcA5SeyB49G0qhMkrW
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - backend

  api-node:
    <<: *x-api-common
    image: api-node:1
    container_name: api-node
    ports:
      - 3000:3000

  api-golang:
    <<: *x-api-common
    image: api-golang:1
    container_name: api-golang
    ports:
      - 8080:8080

  client-react:
    image: client-react:1
    container_name: client-react
    volumes:
      - ./client-react/vite.config.js:/usr/src/app/vite.config.js
    ports:
      - 5173:5173
    links:
      - api-node
      - api-golang
    networks:
      - frontend

  client-nginx:
    image: client-nginx:1
    container_name: client-nginx
    ports:
      - 80:8080
    links:
      - api-node
      - api-golang
    networks:
      - frontend

volumes:
  pg-data:
networks:
  backend:
  frontend:
